# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bp_pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=200)),
                ('inhoud', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bp_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_naam', models.CharField(max_length=200)),
                ('pr_beschrijving', models.TextField()),
                ('pr_cat', models.CharField(max_length=200)),
                ('pr_subcat', models.CharField(max_length=200)),
                ('pr_prijs', models.IntegerField()),
                ('pr_image', models.CharField(max_length=200)),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
                ('new', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bp_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=200)),
                ('achternaam', models.CharField(max_length=200)),
                ('straat', models.CharField(max_length=200)),
                ('nummer', models.IntegerField()),
                ('postcode', models.CharField(max_length=200)),
                ('plaats', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
