# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0002_bp_pages_over_ons'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('onderwerp', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
