# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactModel',
        ),
    ]
