# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0005_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
        migrations.AlterModelOptions(
            name='bp_pages',
            options={'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
        migrations.AlterModelOptions(
            name='bp_products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Producten'},
        ),
        migrations.AlterModelOptions(
            name='bp_users',
            options={'verbose_name': 'Gebruikers', 'verbose_name_plural': 'Gebruikers'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contactformulier', 'verbose_name_plural': 'Contactformulier'},
        ),
    ]
