# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0006_auto_20170621_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bp_products',
            name='pr_image',
        ),
        migrations.AddField(
            model_name='bp_products',
            name='file',
            field=models.FileField(default=None, upload_to='pictures/'),
        ),
    ]
