# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0007_auto_20170710_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bp_products',
            name='file',
            field=models.FileField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='bp_products',
            name='new',
            field=models.CharField(choices=[('NEW', 'NEW'), ('NOTNEW', 'NOTNEW')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bp_products',
            name='pr_cat',
            field=models.CharField(choices=[('bracelets', 'bracelets'), ('kettingen', 'kettingen')], max_length=200),
        ),
        migrations.AlterField(
            model_name='bp_products',
            name='pr_subcat',
            field=models.CharField(choices=[('leather', 'leather'), ('sil_bal', 'Silver Balled'), ('sil_chain', 'Silver Chained'), ('beads', 'Beads')], max_length=200),
        ),
    ]
