# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0009_auto_20170712_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bp_products',
            name='file',
            field=models.ImageField(upload_to=b''),
        ),
    ]
